 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pets", type: :request do
  # Pet. As you add validations to Pet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:my_dog)
  }

  describe "GET /new" do
    it "renders a successful response" do
      get new_pet_url
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Pet" do
        expect {
          post pets_url, params: { pet: valid_attributes }
        }.to change(Pet, :count).by(1)
      end

      it "redirects to the created pet" do
        post pets_url, params: { pet: valid_attributes }
        expect(response).to redirect_to(root_path)
      end
    end
  end
end
